export const footerLinks = {
    Support: [
        "Help Center",
        "Safety Information",
        "Cancellation Options",
        "Our COVID-19 Response",
        "Supporting People with Disabilities",
        "Report a Neighborhood Concern",
    ],
    Community: [
        "Airbnb.org: Disaster Relief Housing",
        "Support Afghan Refugees",
        "Combating Discrimination",
        "Celebrating Diversity & Belonging",
        "Accessible Travel",
        "Guest Referrals",
        "Gift Cards",
    ],
    Hosting: [
        "Try Hosting",
        "AirCover: Protection for Hosts",
        "Explore Hosting Resources",
        "Visit Our Community Forum",
        "How to Host Responsibly",
        "Host an Online Experience",
    ],
    About: [
        "Newsroom",
        "Learn About New Features",
        "Letter from Our Founders",
        "Careers",
        "Investors",
        "Airbnb Luxe",
    ],
}